=== gspandy/fed4j/schema/ysm/OvertureSearchResults.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified">
  <xsd:include schemaLocation="market.xsd"/>
  <xsd:include schemaLocation="currency.xsd"/>

  <xsd:element name="Results" type="ResultsType"/>

  <xsd:complexType name="ResultsType">
    <xsd:sequence>
      <xsd:element
        name="KeywordsRatingSet"
        type="KeywordsRatingSetType"
        minOccurs='0'
        maxOccurs='1'/>
      <xsd:element
        name="PageRegionSet"
        type="PageRegionSetType"
        minOccurs='0'
        maxOccurs='unbounded'/>
      <xsd:element
        name="Local"
        type="LocalType"
        minOccurs='0'
        maxOccurs='1'/>
      <xsd:element
        name="ResultSet"
        type="ResultSetType"
        minOccurs='0'
        maxOccurs='unbounded'/>
      <xsd:element
        name="NextArgs"
        type="NextArgsType"  minOccurs='0' maxOccurs='1'/>
      <xsd:element
        name="PrevArgs"
        type="NextArgsType"  minOccurs='0' maxOccurs='1'/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="KeywordsRatingSetType">
    <xsd:sequence>
      <xsd:element
        name="Sensitive"
        type="SensitiveType" minOccurs='0' maxOccurs='1'/>
      <xsd:element
        name="Market"
        type="MarketType" minOccurs='0' maxOccurs='1'/>
      <xsd:element
        name="Commercial"
        type="xsd:boolean" minOccurs='0' maxOccurs='1'/>
      <xsd:sequence>
        <xsd:element name="Label" minOccurs='0' maxOccurs='unbounded'>
          <xsd:complexType>
            <xsd:simpleContent>
              <xsd:extension base="xsd:string">
                <xsd:attribute name="type" type="xsd:string"/>
              </xsd:extension>
            </xsd:simpleContent>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:sequence>
    <xsd:attribute name="keywords" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="PageRegionSetType">
    <xsd:sequence>
      <xsd:element name="PageRegion" minOccurs='0' maxOccurs='unbounded'>
        <xsd:complexType>
          <xsd:attribute name="name"       type="NonEmptyString" use="required"/>
          <xsd:attribute name="numResults" type="xsd:integer"    use="required"/>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="LocalType">
    <xsd:sequence>
      <xsd:element name="ImplicitLocal" minOccurs='0' maxOccurs='1'>
        <xsd:complexType>
          <xsd:simpleContent>
            <xsd:extension base="xsd:string">
              <xsd:attribute name="type" type="xsd:string"/>
            </xsd:extension>
          </xsd:simpleContent>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="MapURL" minOccurs='0' maxOccurs='1'>
        <xsd:complexType>
          <xsd:simpleContent>
            <xsd:extension base="xsd:string">
              <xsd:attribute name="type" type="xsd:string"/>
            </xsd:extension>
          </xsd:simpleContent>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="Reason" minOccurs='0' maxOccurs='1'>
        <xsd:complexType>
          <xsd:simpleContent>
            <xsd:extension base="xsd:string">
              <xsd:attribute name="type" type="xsd:string"/>
            </xsd:extension>
          </xsd:simpleContent>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:simpleType name="SensitiveType">
    <xsd:restriction base="xsd:integer">
      <xsd:enumeration value="1"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="AdultRatingType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="G"/>
      <xsd:enumeration value="X"/>
      <xsd:enumeration value="U"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="ResultSetType">
    <xsd:sequence>
      <xsd:element
        name="MetaData"
        type="MetaDataType"  minOccurs='0' maxOccurs='1'/>
      <xsd:element
        name="Listing"
        type="ListingType"   minOccurs='0' maxOccurs='unbounded'/>
      <xsd:element
        name="NextArgs"
        type="NextArgsType"  minOccurs='0' maxOccurs='1'/>
      <xsd:element
        name="PrevArgs"
        type="NextArgsType"  minOccurs='0' maxOccurs='1'/>
    </xsd:sequence>
    <xsd:attribute name="id"         type="NonEmptyString" use="optional"/>
    <xsd:attribute name="numResults" type="xsd:integer"    use="optional"/>
    <xsd:attribute name="trackUrl"   type="TrackUrlType"   use="optional"/>
    <xsd:attribute name="comm"       type="xsd:boolean"    use="optional"/>
    <xsd:attribute name="adultRating" type="AdultRatingType" use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="MetaDataType">
    <xsd:sequence>
      <xsd:element name="TotalHits" minOccurs='0' maxOccurs='1' type="xsd:integer"/>
      <xsd:element name="DeepHits" minOccurs='0' maxOccurs='1' type="xsd:integer"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ListingType">
    <xsd:sequence>
      <xsd:element name="ClickUrl" minOccurs='1' maxOccurs='unbounded'>
        <xsd:complexType>
          <xsd:simpleContent>
            <xsd:extension base="xsd:string">
              <xsd:attribute name="type" type="xsd:string"/>
            </xsd:extension>
          </xsd:simpleContent>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="rank"             type="xsd:integer"    use="required"/>
    <xsd:attribute name="title"            type="NonEmptyString" use="required"/>
    <xsd:attribute name="description"      type="NonEmptyString" use="required"/>
    <xsd:attribute name="siteHost"         type="NonEmptyString" use="required"/>
    <xsd:attribute name="promoPhone"       type="NonEmptyString" use="optional"/>
    <xsd:attribute name="bid"              type="BidType"        use="optional"/>
    <xsd:attribute name="bidText"          type="NonEmptyString" use="optional"/>
    <xsd:attribute name="currency"         type="CurrencyType"   use="optional"/>
    <xsd:attribute name="biddedListing"    type="xsd:boolean"    use="optional"/>
    <xsd:attribute name="lat"              type="NonEmptyString" use="optional"/>
    <xsd:attribute name="lon"              type="NonEmptyString" use="optional"/>
    <xsd:attribute name="partnerAccountID" type="NonEmptyString" use="optional"/>
    <xsd:attribute name="adultRating"      type="AdultRatingType" use="optional"/>
    <xsd:attribute name="lastModified"     type="xsd:dateTime"   use="optional"/>
    <xsd:attribute name="businessCountry"  type="xsd:string" use="optional"/>
    <xsd:attribute name="siteLang"         type="xsd:string" use="optional"/>
    <xsd:attribute name="listingLang"      type="xsd:string" use="optional"/>
    <xsd:attribute name="resultType"       type="NonEmptyString" use="optional"/>
    <xsd:attribute name="rawscore"         type="xsd:string"      use="optional"/>
    <xsd:attribute name="tightmatchresulttype" type="xsd:string"  use="optional"/>
  </xsd:complexType>

  <xsd:complexType name="DirectoryType">
    <xsd:attribute name="title"   type="NonEmptyString" use="required"/>
    <xsd:attribute name="did"     type="xsd:integer"    use="required"/>
    <xsd:attribute name="level"   type="xsd:integer"    use="required"/>
    <xsd:attribute name="uriArgs" type="NonEmptyString" use="required"/>
  </xsd:complexType>

  <xsd:simpleType name="TrackUrlType">
    <xsd:restriction base="xsd:token">
      <xsd:pattern value="http:\/\/a840.g.akamai.net\/.*"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="BidType">
    <xsd:restriction base="xsd:token">
      <xsd:pattern value="\p{Nd}+([\.,]\p{Nd}{2})?"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="NonEmptyString">
    <xsd:restriction base="xsd:string">
      <xsd:minLength value='1'/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="NextArgsType">
    <xsd:restriction base="xsd:token">
      <xsd:pattern value="Keywords=.*&amp;xargs=.*"/>
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== gspandy/fed4j/schema/ysm/ysm.xml
<?xml version="1.0" encoding="UTF-8"?>
<Results xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://dtd.overture.com/schema/affiliate/2.9.1.1/OvertureSearchResults.xsd">
 <KeywordsRatingSet keywords="flower">
  <Market>us</Market>
  <Commercial>false</Commercial>
  <Label type="state">E</Label>
 </KeywordsRatingSet>
 <PageRegionSet>
  <PageRegion name="North" numResults="4"></PageRegion>
  <PageRegion name="South" numResults="2"></PageRegion>
  <PageRegion name="East" numResults="8"></PageRegion>
 </PageRegionSet>
  <SearchID>F14DE2F50CE9D39C</SearchID>
 <canonQuery>flower</canonQuery>
 <spCanonQuery>flower</spCanonQuery>
 <resultDepth>76</resultDepth>
 <acceptDepth>23</acceptDepth>
 <moreResults>0</moreResults>
 <SSRQB>BIcAAGQWBE0C9Be2DFsdDQNEVfAEBA8PAAAAAAAAAAAAAAdiAA==</SSRQB> <ResultSet id="searchResults" numResults="12" adultRating="G" searchId="F14DE2F50CE9D39C">
  <Listing rank="1" title="$10 Off Teleflora® &lt;strong&gt;Flowers&lt;/strong&gt;" description="Delight Friends with a Floral Gift. Same Day Local Delivery." siteHost="www.&lt;strong&gt;teleflora.com&lt;/strong&gt;" biddedListing="true" bid="6.07" cost="3.62" accountId="1456850624" adultRating="G" resultType="OTU" flags="paypal" term_id="266942874511" crtv_id="39275861511" ad_group_id="16302308399" campg_id="4020787511" canonq="flower" spcanonq="flower" clkb="1.661" SSRB="CwAAAAAABzrNB+MIAwFqJxDeBTAH4wAABnwAAAABACcCXwCWAMsAAKsUAAAAAA==">
   <ClickUrl type="4-North">http://rc12.overture.com/d/sr/?xargs=15KPjg16JSmpamwr%2DucbrASeOEwFoaxca59stsD5ZxGNBf8WQ8De1%2DaKDBmcZ4Re9u5xiBkP%2DV%5FaAQKvrzmv2CFQqJQlaOHOb23pqVk4Y%2DP62mXNlBhhca%5FrXknIBINXsEamm11eOOp67BJtb%2DP2gav4IAyx%2DZ64I2gsK3weAeFbLa2DZKy3yFLJ8Zk%5F9rxZTVeMgEPLNRC6yb5SOWA%2DlJv9984%5Fv1bS0SeBuSx24N3i6GLTR3oKu4atAEvrfvmY%2DGbP3%5Fmc8PP0nFqKskvVyAmCuK3LomIW6ytOVUkEhVHKa1MWKC12R3qaa%5FpsqfJNR172iiSNqITTHEWwF2ekFnA%2DHkPEOPKGAd0i4%2E</ClickUrl>
  </Listing>
  <Listing rank="2" title="&lt;strong&gt;Flowers&lt;/strong&gt; at 1-800-&lt;strong&gt;FLOWERS&lt;/strong&gt;®" description="Same Day Delivery Available. Featuring Martha Stewart &lt;strong&gt;Flowers&lt;/strong&gt;." siteHost="&lt;strong&gt;1800flowers.com&lt;/strong&gt;" biddedListing="true" bid="3.34" cost="3.07" accountId="1259633190" adultRating="G" resultType="DB" term_id="49411783012" crtv_id="24931725012" ad_group_id="2280589900" campg_id="938377012" canonq="flower" spcanonq="flower" clkb="1.799" SSRB="CwAAAAAABmNICNEKsgEzJxDeBZ8I0QAABwcAAAABACcBTgBvAMsAAC0yAAAAAA==">
   <ClickUrl type="4-North">http://rc12.overture.com/d/sr/?xargs=15KPjg16BSnJamwr%2DocbXOT%2DCDy14axca5%2D8hmDJZ%2DH9Rc5iMxXOJ9ZqPEk8xxTexxv1PdzPGd%5FK8SLPv6nvqMEAiIRFaNEebpjdLJz480Na6mW9TnsYRzy%2D7gmodPO3cFyl%2DBeZKzne3IIMCofnNI%5FogD227Bvvxvwsi%2DzOEcF7Pc0EQpqlHQPOVbr%2DRxl52RJOwITsYgfa%2Dck1XjeehDwq9jwb6pPnAiGAij5Rt4rFOELDF61LiScYgLp7bxhIqGa%2DbrzY1TPRjMs6Eh%5Fk%5FD3mutjJ13Bkq%2D375Zhg9TRuKtOGWC51MuoK%5FJ3bbWIcoy5j2tX52DV0LOIk97ahQzX6P%5FbVjfBFEM</ClickUrl>
  </Listing>
  <Listing rank="3" title="FTD® Official Site" description="$19.99 &lt;strong&gt;Flowers&lt;/strong&gt;. Same Day Delivery. Sale: Free Vase - Shop Now." siteHost="www.&lt;strong&gt;FTD.com&lt;/strong&gt;" biddedListing="true" bid="3.55" cost="2.36" accountId="1523767567" adultRating="G" resultType="DB" flags="paypal" term_id="6034870522" crtv_id="26428724522" ad_group_id="342811910" campg_id="39225522" canonq="flower" spcanonq="flower" clkb="1.553" SSRB="CwAAAAAADl5nBzAIcQDsJxDeBNoHMAAABhAAAAABACcBYwB9AMsAABvvAAAAAA==">
   <ClickUrl type="4-North">http://rc12.overture.com/d/sr/?xargs=15KPjg16RSnpamwr%2Dvdr%5FPSuSHxFkaxca58cJsDZR8HddIoS5gUuR9ZqLAksR4W7064w%5FRzfCX%2Da4fLPPymfyKEgqOQFCOD7Kh0Y7CyYk1Ma2l5edx2L4qxuntloFOmE42fS68ete7nvidYdv7PHhL6PxbjhCY9PBswcu%2Dw%2DcWBuuJ1VZlhQOWZcMSvPIk983HXe8LPLdVDKyQ5yWfA4oRmNF1wN2UHSETXF%2Dk7WsEq1%5F1Mm9ypqzTf48XvKvzn5nJPe6rwIYZPgaFpaF0%5FS7T3mqt%2DbY1O3qU2ORU2Q9cFPSTODvViR1%2D7KPXmqODJN9172rvevWaGnHhMAB2fFMgX6LIDGU%2E</ClickUrl>
  </Listing>
  <Listing rank="4" title="Send &lt;strong&gt;Flowers&lt;/strong&gt; from $19.99" description="Send Roses, Lilies &amp; other &lt;strong&gt;Flowers&lt;/strong&gt;. Best Value - Wall Street Journal." siteHost="www.&lt;strong&gt;ProFlowers.com&lt;/strong&gt;" biddedListing="true" bid="2.15" cost="1.83" accountId="5233" adultRating="G" resultType="OTU" term_id="10208465012" crtv_id="5600681512" ad_group_id="158581900" campg_id="21513512" canonq="flower" spcanonq="flower" clkb="1.698" SSRB="CwAAAAAAB+T+CCMICQC3JxDeBU4IIwAABqIAAAABACcA1wCEAMsAABBBAAAAAA==">
   <ClickUrl type="4-North">http://rc12.overture.com/d/sr/?xargs=15KPjg165Slpamwruod7%5FeHbiPwF8JlZ6x88l4Xs10HtBW9XpsWOB%5FePKcls14SOlj7g%5FXzvWS%5FKYQLPT9mfOcQ1CDQFWJGeX33Tjy9dQwN6%2DjWdlDgbYsl9Kp3r9%2DJn8QMy%2D8eNq9nvi%5FeJX0PnlL%5Fo4DyBWZ%2Duc%5FkMKy2JlBUv6AzgMq9irVJe9x79Ysgb%2D2IO4KQ8FDLoqUk3amQL9ByqgBluSgNiEXXT396WgOtFmAOjVho6vbLdsE7%2Dmu3draf7Koi8xuLlOHxMRfvhOW3y%5FKxMMybiXd5utYmF8SGu%5FxaCyM0AYrvv%2DFzMHhatFluib%2DC8HZASD6YGNLTA%2E%2E</ClickUrl>
  </Listing>
  <Listing rank="5" title="Free Delivery, FTD &lt;strong&gt;Flowers&lt;/strong&gt;" description="Free delivery for online orders. FTD florist satisfaction guaranteed." siteHost="www.&lt;strong&gt;ftdfloristsonline.com&lt;/strong&gt;/&lt;strong&gt;flower&lt;/strong&gt;s" biddedListing="true" bid="1.90" cost="1.75" accountId="1040135995" adultRating="G" resultType="OTU" term_id="457468522" crtv_id="398204522" ad_group_id="13996410" campg_id="7369522" canonq="flower" spcanonq="flower" clkb="1.631" SSRB="CwAAAAAAAZxsB7IGZACvJxDeBRkHsgAABl4AAAABACcAvgCNAMsAAAAAAAAAAA==">
   <ClickUrl type="4-South">http://rc12.overture.com/d/sr/?xargs=15KPjg16hSlZamwr%2DqcLzJT%2DaLy1saxca59choBpR7HcMPrH9sUul2aKfAm9MpEOFl7wjQyvGS%2D6UeJfLznfOCEQuPUwLXFOD21I7EyScIA%5FCsXdRAg7UkZtvZnsZDPXYGYnjgON%2D%5FmevMNqWhfHNK%5F4cCzh2Z9fdsx9nnlOoaDdmHnRYg7Q2GLO0F6dRcg7rGKel8Q8ZWdqqPwnWbcMxw%2D%5F90kZnQOCkWICqnkXlTp12COjN%5Fv6vTfoof6OH8zNPHLra%5FiogLfFGjseN32C6qn3Od39s0OzPT0ewG%5FwYFQ6rqMX7QgB1%2D8KPamqOBae9Z%5FT2pTdqIVXz3dxN2fWRBYg%2E%2E</ClickUrl>
   <ClickUrl type="4-East">http://rc12.overture.com/d/sr/?xargs=15KPjg169SlZamwr%2DqcLzJT%2DaLy1saxca59choBpR7HcMPrH9sUul2aKfAm9MpEOFl7wjQyvGS%2D6UeJfLznfOCEQuPUwLXFOD21I7EyScIA%5FCsXdRAg7UkZtvZgcZDPXYGYnjgON%2D%5FmevMNqWhfHNK%5F4cCzh2Z9fdsx9nnlOoaDc%2DJmxZuqg7ZV5oAmdUr98nDWu8APrFcDM%5FIwCuWIKxw6N105JmiNyQaKS7X8jABrVieJzBhpLDPeZlY7binxtDfPKHrzYxJfnTW4%2DBT2CLAxH6LmN1ufyva1uw2yF8MSr2tJDfVnlp3pavJ3aibGuYgszarX52bGnHhME96XXVB</ClickUrl>
  </Listing>
  <Listing rank="6" title="Same Day &lt;strong&gt;Flowers&lt;/strong&gt; Starting at $24.99" description="Same Day &amp; Weekend Delivery &lt;strong&gt;Flowers&lt;/strong&gt;. 100% Satisfaction Guarantee." siteHost="www.&lt;strong&gt;FromYouFlowers.com&lt;/strong&gt;" biddedListing="true" bid="1.35" cost="1.20" accountId="1023339752" adultRating="G" resultType="OTU" flags="paypal" term_id="31127894013" crtv_id="7216079513" ad_group_id="871475401" campg_id="120076513" canonq="flower" spcanonq="flower" clkb="2.107" SSRB="CwAAAAAAAVSyCvkIJgB4JxDeBpUK+QAACDoAAAABACcAhwB4AMsAAAAAAAAAAA==">
   <ClickUrl type="4-South">http://rc12.overture.com/d/sr/?xargs=15KPjg16ZSkZamwr%2Dqdr%5FLT%2DqFx1waxca588luD5Z%5FGtRd5iMxXOh4b6fGnsF4TPo2swPUzPWU%5FKcTKPb7n%5FuNFgyJRlGJD7Kh0YvGzI09MaYVb%2DkYirAtx%2Djulo9KPC8%2DVC68eNG7nvidYXLDD2xdjddAwBya%2DvFmwsu%2DweYcBuuJ1VZlmAORZcMSvPIk983HXe8LPLdVDKyQ5yWfA4oRmNF1wN2UHSETXF%2Dk7WsEq1%5F1Mm9ypqzTf48XvKvzn5nJPe6rwIYZPgaFpaF0%5FS7T3mqt%2DbY1O3qU2ORU2Q9cFPSTODvViR1%2D7KPXmqODJNp172rvevaaGnfzdxM5cUVnA67oHWXu</ClickUrl>
   <ClickUrl type="4-East">http://rc12.overture.com/d/sr/?xargs=15KPjg16VSkZamwr%2Dqdr%5FLT%2DqFx1waxca588luD5Z%5FGtRd5iMxXOh4b6fGnsF4TPo2swPUzPWU%5FKcTKPb7n%5FuNFgyJRlGJD7Kh0YvGzI09MaYVb%2DkYirAtx%2Djulo9KPC8%2DVC68eNG7nvidYXLDD29djddAwBya%2DvFmwsu%2DweYcBuuJ1VZljg2XZY1Vv61fgMi3XJh%5FT7ImCtDtkC%5FlZs0TxtwloN2HPyFmXC2r4GcNry%2DWez14o7DOfJEMp7f0jN7MZLWhw54LKVLCoeN22FuB3U6t9dxuNmzT3r4QwQZbFMSkYTLcnlprpabJ3arWL8oy5HCcc4%5FUEXXhMAB2fFMgX6LIDGU%2E</ClickUrl>
  </Listing>
  <Listing rank="7" title="50% Off Same Day &lt;strong&gt;Flowers&lt;/strong&gt;" description="All &lt;strong&gt;Flowers&lt;/strong&gt; on the Site are 50% Off. Take Advantage and Buy Today." siteHost="www.&lt;strong&gt;BloomsToday.com&lt;/strong&gt;" biddedListing="true" bid="0.98" cost="0.97" accountId="3690100940" adultRating="G" resultType="QuAd,KingKong" term_id="153967311022" crtv_id="34674162022" ad_group_id="7654891910" campg_id="4615515522" canonq="flower delivery same day" spcanonq="flower delivery same day" clkb="2.066" SSRB="CwAAAAAAAPgrDFsKUABhJxDe/BgMWwAACBEAAAIAACcAYgAtAMsAAAAAAAAAAA==">
   <ClickUrl type="4-East">http://rc12.overture.com/d/sr/?xargs=15KPjg17JSj5amwr2sfbzJTOOLxl4axca59s1vCpR4GtBc8mQ8De14aKbFk8x5RO1n%2DF%2DNwPOW%2D6AeKvX8kfKKGwqHGWW1GuLpjdLJzo87MaugX9NHx4UUmefom4VHOngFY28dSOKj3uPFKNbvbj9G94gD227BvvxvwsqwzOcaFLze3kQpqlHQPO5VruQ%5F0J7OX5sNPsdXCdyZ4FOfBJ9JuMokw%2DCkbhAiCyqjkBsKo16IJTUKt%5FHAe40XurXvn5GabPWsyNQINxvUobZ1uUuB3E7YPbtTJmrW3O8A1gtGAru%5FMWeImF9%2D4biO2v%5FbP400s3n%2DEZOGeCn2aUNtLQF8WrW4ZFjZMzBmoi29MJhHd9%5F%5FuC63FuCLDAEXUg%2E%2E</ClickUrl>
  </Listing>
  <Listing rank="8" title="Florists Hayward" description="Delivery Service To Home &amp; Office. &lt;strong&gt;Flowers&lt;/strong&gt; For Any Occasion." siteHost="www.&lt;strong&gt;HaywardFlowers.com&lt;/strong&gt;" biddedListing="true" bid="2.50" cost="2.47" accountId="4068923540" adultRating="G" resultType="DB" term_id="204811284512" crtv_id="22160171012" ad_group_id="7360256400" campg_id="4102894012" canonq="flower" spcanonq="flower" clkb="0.801" SSRB="CwAAAAAAAAkGA2EB8AD3JxDeAoEC3wHwAyEAAAABACcA+gCSAMsAAAAAAAAAAA==">
